### ISSUE TITLE
Power-Platform-Blog-Updates Sample Solution Gallery does not redirect to this repository. 

### ISSUE THREAD

**Issue by NatiTurts** [pnp/powerplatform-samples#104]
Hi :)

## Steps to Reproduce

1. Go to https://adoption.microsoft.com/en-us/sample-solution-gallery/sample/pnp-powerplatform-samples-Power-Platform-Blog-Updates/
2. Click on View on Github or Download from Github
3. See error
4. There also seems to be an issue with the thumbnail. 

Thanks for all the work and support the PnP team provide.

**Comment by Laskewitz** [comment]
Just merged a PR that fixes this. Should be fixed in the Sample Solution Gallery at the next sync! Thanks for creating the issue!
