### ISSUE TITLE
New Sample: License Calculator

### ISSUE THREAD

**Issue by kkazala** [pnp/powerplatform-samples#72]
### Sample

https://github.com/pnp/powerplatform-samples/tree/main/samples/license-calculator

### Author(s)

@kkazala

### Question

My PR was approved yesterday, but I still not's see the sample in https://pnp.github.io/powerplatform-samples/samples/powerapps/
Is there something I need to do?

**Comment by Katerina-Chernevskaya** [comment]
Hi @kkazala ,

The main Sample Gallery is here: https://adoption.microsoft.com/en-us/sample-solution-gallery/?keyword=&sort-by=updateDateTime-true&page=1&product=Power+Apps

Here is the direct link to your sample in the Sample Solution Gallery: https://adoption.microsoft.com/en-us/sample-solution-gallery/sample/pnp-powerplatform-samples-license-calculator/

Regards,
Katerina Ch.

**Comment by kkazala** [comment]
Ah, gotcha. I saw the adoption site, I just thought the https://pnp.github.io/powerplatform-samples/ should also be updated. For some reason, it’s positioned much higher in search results when looking for power apps samples :) thank you for the explanations :)
Kinga
________________________________
