### ISSUE TITLE
Weeky TimeSheet Notification 

### ISSUE THREAD

**Issue by SafaElfetouri** [pnp/powerplatform-samples#75]
<img width="506" alt="Screenshot 2024-02-12 140103" src="https://github.com/pnp/powerplatform-samples/assets/60845618/6f26f83d-de54-4470-8d27-9f4e0553d9ec">

Hi,
I downloaded the solution successfully... but I saw this notification (One or more commands are unavailable due to your current privileges for this environment)

 Thanks in advance

**Comment by aprildunnam** [comment]
That sounds like an issue with your permissions in the environment.  You need at least Basic User and System Customizer to import solutions
