### ISSUE TITLE
The is an error in this formula

### ISSUE THREAD

**Issue by dpclay** [pnp/powerplatform-samples#91]
## Installation

* [Download](./solution/weekly-timesheet-sharepoint.zip) the `.zip` from the `solution` folder
* Within **Power Apps Studio**, import the solution `.zip` file using **Solutions** > **Import Solution** and select the `.zip` file you just packed.
* Open the Timesheet Template app in Edit mode
* Go to the datasources tab and remove the BillTo and TimeEntries tables
![MyTimeCards](assets/deleteBillTO.png)
![MyTimeCards](assets/deleteTimeEntries.png)
* In the datasources tab, click add new and search for SharePoint
![AddData](assets/addSP.png)
* Navigate to where you created the lists and add the TimeEntries and BillTo list to your app
![AddData](assets/addSPLists.png)
* Save and Publish

## Steps to Reproduce

1. Go to 'Power Apps Weekly TimeCard Template - SP'
2. Click on 'edit'
3. See error in edit mode.

## see images
<img width="1712" alt="timesheeterror2" src="https://github.com/pnp/powerplatform-samples/assets/115174151/25c0f173-93c4-44ff-b149-a0b263e5639a">
<img width="1310" alt="timesheetissue" src="https://github.com/pnp/powerplatform-samples/assets/115174151/66e729da-00c6-4855-b466-55bd2076af60">
 of the issue

**Comment by dpclay** [comment]
Any chance i could get some help on this?

**Comment by sudhirke** [comment]
@dpclay I was able to get this to work,  please contact me in case you need help. 

sudhir@spxpert.com
https://www.upwork.com/freelancers/sudhirke
