### ISSUE TITLE
weekly-timesheet-sharepoint - BillTo TimeEntries

### ISSUE THREAD

**Issue by ghost** [pnp/powerplatform-samples#93]
### Sample

weekly-timesheet-sharepoint

### Author(s)

@aprildunnam

### Question

Hi. Thank you. How can I create the BillTo and TimeEntries list? Do you have a step by step tutorial for this? Thank you.

**Comment by Scotty1629** [comment]
did you ever get this working?

**Comment by sudhirke** [comment]
@omidcka Do you have SharePoint site?  Creating a list is easy,  make sure to keep field names similar to what @aprildunnam mentioned in her video.  Just keep "WeekStart" field as "Week Start" (with space). I was able to get it to work within just half an hour
