### ISSUE TITLE
weekly-timesheet-sharepoint - 

### ISSUE THREAD

**Issue by jwise155** [pnp/powerplatform-samples#94]
### Sample

weekly-timesheet-sharepoint

### Author(s)

@aprildunnam

### Question

Followed directions, when creating a new timesheet - cannot save or submit

**Comment by Scotty1629** [comment]
Hi I have same problem, did you fid fix?

**Comment by sudhirke** [comment]
@jwise155 @Scotty1629 This is due to difference in field name "Week Start".  I was able to get this sample to work.  Contact me in case you need help

**Comment by Scotty1629** [comment]
Thanks for your help, I can’t get the approvals to show other than my own.?

**Comment by sudhirke** [comment]
@Scotty1629 

Please check if your Office 365 account has manager property?  Also if you have any other account where your account is setup as manager it will work.

There is some copy paste error when on the Save / Submit button click. I raised an issue on the repository and also put the code changes (pull request under review)

> When you click on new timesheet, fill timesheet and click on Submit,  it automatically updates to your manager.  
> When you create a new timesheet,  click on Save button,  it will keep Employee and Manager information same.
> On My Timesheet page,  both Save and Submit button have same code,  so it never gets updated to Manager information.  

I have applied the fix and got it to working at my end.

**Comment by sudhirke** [comment]
Please check your TimeEntries SharePoint list,  you will see Employee and Manager columns with same information,  that's the reason you can only view and approve your own records.
